### ISSUE TITLE
希望增加使用文档

### ISSUE THREAD

**Issue by rememberber** [SeanDragon/protools#11]
很好的项目，准备应用一下，希望能提供下使用文档

**Comment by SeanDragon** [comment]
您好，如果想使用的话，目前是不在中央仓库，这个要提醒下您；需要本地安装（ `mvn install` ）
如果要使用的话，建议先使用 `DatePlus` 以及 `Decimal` 这两个类，其他的工具类基本都是 `Tool` 为前缀的类
