### ISSUE TITLE
有兴趣投个简历吗? [阿里云 城市大脑 应用开发招聘]

### ISSUE THREAD

**Issue by willkan** [SeanDragon/protools#4]
阿里云 城市大脑 应用开发招聘
团队介绍
阿里云事业群-解决方案与产品事业部-城市大脑事业部-城市大脑研发
，团队内博士大牛云集，团队致力于用大数据解决城市行业中的问题.

团队案例
城市大脑 http://info.secu.hc360.com/2017/10/180854901576.shtml

岗位描述
后端应用开发
语言 JAVA || Node.js, 了解 go 等语种有加分
能独立解决问题，能够负责重要业务模块的需求分析及设计实现，且对线上部署环境比较熟悉，能够独立分析和快速排查线上故障。
熟悉开发语言底层运行机制，如 Java 虚拟机原理,Java 高级特性和类库，Java 网络与服务器编程，Java 多线程编程，常见开源产品
熟练使用下列大多数技术
分层的应用框架设计
分布式系统, 负载均衡，集群技术, 高可用，可容灾分布式系统
缓存，数据同步，大容量数据存储和检索系统设计能力，数据分库分表
大型网站常见架构
熟悉应用发布和运维，线上故障分析和排查
模块 /系统的架构设计能力,掌握常见的架构设计方法和模式
了解前端基本原理，可以独立解决简单的前端问题和开发简单的前端页面
实践测试驱动开发
具备辅导他人的能力和技能，有良好的分享习惯
能持续的关注和学习相关领域的知识，并能使用到工作当中
简历投递： huikang.whk@alibaba-inc 点 com

后端应用架构
具备后端应用开发能力
项目：制定项目中开发计划，控制整个开发的进度；在项目中，协调与其他技术部门在开发上的接口，确定方案; 综合分析能力强，能与不同业务团队沟通协同
业务：能独立带领产品或业务向前发展，独立承担架构规划，建设以及调优，能够全局的规划和解决产品线的业务问题
简历投递： huikang.whk@alibaba-inc 点 com

**Comment by SeanDragon** [comment]
请不要伪造阿里的面试邀请，谢谢。

**Comment by SeanDragon** [comment]
前辈您好，我的微信syl8023who

我的简历:https://seandragon.github.io

**Comment by SeanDragon** [comment]
已回复邮件，咱们加微信细聊，微信号在邮件回复里面。

**Comment by willkan** [comment]
不好意思,我没伪造.   这是我私人邮箱,没经常看. 请问有意愿吗?有意愿的话我先内推下?

2018-01-19 19:23 GMT+08:00 SeanDragon <notifications@github.com>:

**Comment by SeanDragon** [comment]
您加一下我微信吧

syl8023who

**Comment by willkan** [comment]
额,个人原因不方便加微信哈

2018-01-23 19:59 GMT+08:00 SeanDragon <notifications@github.com>:
