### ISSUE TITLE
请问okhttp中FormBody中MediaType默认是"application/x-www-form-urlencoded"，请问怎么修改呢？

### ISSUE THREAD

**Issue by yuffic** [SeanDragon/protools#5]
在ToolSendHttp中FormBody进行Builder中，MediaType属性试过多种方式修改为“application/json;charset=UTF-8”,但最终还是默认的"application/x-www-form-urlencoded"，请问怎样可以设置该参数呢？

**Comment by SeanDragon** [comment]
很抱歉，这么长时间才回复你。

可以改变HttpSend中headers的Content-Type来改变这个值
